"""G-code command registry: single reader for command validity verdicts.

Loads backend/data/gcode_commands.json (generated by
scripts/generate-gcode-registry.py — see that file for provenance) and
answers, for any command token and any parsed project:

  valid            — registered and gating sections present (or ungated),
                     OR a user-defined gcode_macro in the project
  conditional_out  — registered, but the section that loads its extra is
                     absent from the project (e.g. SET_LED without any
                     led-family section)
  unknown          — never registered by stock Klipper (likely confabulated;
                     could also be a third-party plugin extra)

Three verdicts, never a boolean: false-ERRORs that block saves destroy
validator trust, so consumers decide severity. Fuzzy suggestions via
difflib only (stdlib, Pi 3B+ friendly).

User macros are NEVER baked into the JSON — they are layered per-project at
query time (include-order aware, last-def-wins per Klipper semantics).
"""
from __future__ import annotations

import difflib
import json
import re
from dataclasses import dataclass, field
from functools import lru_cache
from pathlib import Path

DATA_PATH = Path(__file__).resolve().parent.parent / "data" / "gcode_commands.json"

STATUS_VALID = "valid"
STATUS_CONDITIONAL_OUT = "conditional_out"
STATUS_UNKNOWN = "unknown"

# Command tokens we never flag regardless of registry state: pure query/
# informational commands Klipper always answers, and traditional-G code
# letters the tokenizer can see in odd positions.
ALWAYS_OK: frozenset[str] = frozenset({"M115", "HELP", "STATUS"})

# Max suggestions attached to an unknown verdict.
_SUGGEST_LIMIT = 3


@dataclass(frozen=True)
class CommandVerdict:
    name: str
    status: str  # STATUS_VALID | STATUS_CONDITIONAL_OUT | STATUS_UNKNOWN
    required_sections: tuple[str, ...] = ()
    suggestions: tuple[str, ...] = ()
    source: str = "registry"  # "registry" | "user_macro"
    extra: str = ""

    @property
    def is_problem(self) -> bool:
        return self.status != STATUS_VALID


@dataclass(frozen=True)
class ProjectGcodeContext:
    """Per-project command availability inputs."""
    section_types: frozenset[str]
    user_macros: frozenset[str]
    registry_alias_collisions: frozenset[str] = field(default_factory=frozenset)


@lru_cache(maxsize=1)
def load_registry(path: str | None = None) -> dict:
    p = Path(path) if path else DATA_PATH
    if not p.is_file():
        raise FileNotFoundError(
            f"{p} missing — run scripts/generate-gcode-registry.py")
    return json.loads(p.read_text())


def normalize_name(name: str) -> str:
    """Klipper command names are matched case-insensitively and only the
    first whitespace-delimited token is the command."""
    return name.strip().split()[0].upper() if name.strip() else ""


def _suggest(name: str, pool: list[str], limit: int = _SUGGEST_LIMIT,
             commands: dict | None = None,
             min_score: float = 0.42) -> tuple[str, ...]:
    """Fuzzy suggestions, stdlib only. Three signals, ranked:

    1. prefix containment (SET_ -> SET_* names, HELP -> HELPP) — 0.75
    2. domain-word hit: an unknown name's word matches one of the
       candidate's gating section types (SET_NEOPIXEL_COLOR -> SET_LED
       because neopixel is in SET_LED's requires_sections). Plain difflib
       can never find this (char ratio ~0.4). — 0.65
    3. difflib char ratio — the general case (RESONANCE_TEST ->
       TEST_RESONANCES scores ~0.93).
    """
    words = set(name.split("_"))
    scored: list[tuple[float, str]] = []
    for cand in pool:
        score = difflib.SequenceMatcher(None, name, cand).ratio()
        if cand.startswith(name) or name.startswith(cand.rstrip("_")):
            score = max(score, 0.75)
        if commands and score < 0.65:
            entry = commands.get(cand)
            if entry:
                gates = {s.upper() for s in entry.get("requires_sections", [])}
                if words & gates:
                    score = max(score, 0.65)
        if score >= min_score:
            scored.append((score, cand))
    scored.sort(key=lambda t: (-t[0], t[1]))
    return tuple(c for _, c in scored[:limit])


def classify_command(
    name: str,
    context: ProjectGcodeContext | None = None,
    registry: dict | None = None,
) -> CommandVerdict:
    """Classify one command token against the registry + project context.

    context=None validates against the raw registry only (name exists or
    not; gated commands report valid-ungated — callers doing per-project
    checks must pass a context).
    """
    reg = registry or load_registry()
    canonical = normalize_name(name)
    if not canonical:
        return CommandVerdict(name, STATUS_UNKNOWN, suggestions=())
    if canonical in ALWAYS_OK:
        return CommandVerdict(canonical, STATUS_VALID, source="registry")

    commands = reg["commands"]
    entry = commands.get(canonical)

    if context and canonical in context.user_macros and entry is None:
        return CommandVerdict(canonical, STATUS_VALID, source="user_macro")

    if entry is None:
        pool = sorted(set(commands) | (context.user_macros if context else set()))
        suggestions = _suggest(canonical, pool, commands=commands)
        return CommandVerdict(canonical, STATUS_UNKNOWN,
                              suggestions=suggestions)

    required = tuple(entry.get("requires_sections", []))
    if required and context is not None:
        if not context.section_types.intersection(required):
            return CommandVerdict(
                canonical, STATUS_CONDITIONAL_OUT,
                required_sections=required,
                source="registry", extra=entry.get("extra", ""))
    return CommandVerdict(canonical, STATUS_VALID,
                          required_sections=required,
                          extra=entry.get("extra", ""))


# ── per-project resolver ────────────────────────────────────────────────

# gcode body params: the `gcode` param of [gcode_macro]/[delayed_gcode], plus
# display/other multiline values we must NOT scan for commands.
_GCODE_PARAM_KEYS = {"gcode", "gcode_on_error"}
# section types whose bodies are real gcode executed by the printer
_GCODE_SECTION_TYPES = {"gcode_macro", "delayed_gcode"}


def build_project_context(configs: dict) -> ProjectGcodeContext:
    """Collect section types + user macro names across a parsed project.

    configs: dict[filename, ConfigFile] (backend.parser.config_parser).
    Include-order aware is approximated by union across files that are
    actually reachable via [include]; for availability (not definition
    precedence) a union is correct and last-def-wins cannot demote a name
    below "exists".
    """
    section_types: set[str] = set()
    user_macros: set[str] = set()
    for config in configs.values():
        for section in getattr(config, "sections", []):
            if getattr(section, "is_commented_out", False):
                continue
            section_types.add(section.section_type)
            if section.section_type == "gcode_macro":
                rename = section.get_value("rename_existing", "").strip()
                macro = section.section_name.strip().upper()
                if macro:
                    user_macros.add(macro)
                # rename_existing means the ORIGINAL command stays
                # available under its registry name (e.g. a PRINT_START
                # wrapping G28 keeps G28 valid).
                if rename:
                    user_macros.discard(rename.upper())
    return ProjectGcodeContext(
        section_types=frozenset(section_types),
        user_macros=frozenset(user_macros))


def available_commands(configs: dict) -> set[str]:
    """All command names valid for this project: registry names whose gates
    are satisfied, plus user macros."""
    reg = load_registry()
    ctx = build_project_context(configs)
    names = set(ctx.user_macros) | set(ALWAYS_OK)
    for name, entry in reg["commands"].items():
        required = entry.get("requires_sections", [])
        if not required or ctx.section_types.intersection(required):
            names.add(name)
    return names


# ── gcode body token scan ───────────────────────────────────────────────

_JINJA_BLOCK_RE = re.compile(r"^\s*\{%.*%\}\s*$")
_COMMENT_RE = re.compile(r";.*$")
_CMD_TOKEN_RE = re.compile(r"^[A-Za-z][A-Za-z0-9_]*$")
# Lines that are macro definition/param plumbing, not executed commands:
#   {% macro ... %} handled by block regex; `output +=` etc handled by
#   token regex (has spaces / symbols).
_PARAM_CONT_RE = re.compile(r"^(\w+):\s*(.*)$")  # key: value continuation start


def _strip_jinja_inline(line: str) -> str:
    """Remove {expression} and {%...%} spans so `SET_LED LED={led}` checks
    only SET_LED; keeps the command token position."""
    out = re.sub(r"\{[%{].*?[%}]}", " ", line)
    return out


def iter_gcode_command_tokens(text: str):
    """Yield (line_no, token) for command tokens in gcode body text.

    Handles Klipper's two execution shapes inside config files:
      1. [gcode_macro]/[delayed_gcode] bodies: the `gcode:` param, whose
         value lines are INDENTED continuation lines.
      2. single-line `gcode: <commands>` and `;`-separated / multi-statement
         values are not valid Klipper — one statement per line.
    Jinja control-flow lines, jinja expression spans, comments, blank
    lines, and non-token text are skipped.
    """
    for i, raw in enumerate(text.splitlines(), start=1):
        line = _COMMENT_RE.sub("", raw).strip()
        if not line:
            continue
        if _JINJA_BLOCK_RE.match(raw):
            continue
        line = _strip_jinja_inline(line)
        if not line.strip():
            continue
        # first token; a `key:`-shaped token (trailing colon) is a config
        # param line, not a command (e.g. `variable_foo: 1` when scanning
        # a whole section).
        token = line.split()[0]
        if token.endswith(":"):
            continue
        if not token or not _CMD_TOKEN_RE.match(token):
            continue
        yield i, token.upper()


def scan_gcode_body(text: str, context: ProjectGcodeContext | None = None):
    """Yield (line_no, CommandVerdict) for problem verdicts in a body.

    Only conditional_out/unknown are yielded; valid tokens produce nothing.
    """
    for line_no, token in iter_gcode_command_tokens(text):
        verdict = classify_command(token, context)
        if verdict.is_problem:
            yield line_no, verdict


def _cli(argv: list[str]) -> int:
    """python3 -m backend.services.gcode_registry NAME [NAME...]"""
    reg = load_registry()
    for raw in argv:
        v = classify_command(raw, registry=reg)
        detail = ""
        if v.status == STATUS_UNKNOWN and v.suggestions:
            detail = f" did you mean: {', '.join(v.suggestions)}?"
        elif v.status == STATUS_CONDITIONAL_OUT:
            detail = f" requires one of: {', '.join(v.required_sections)}"
        print(f"{v.name}: {v.status} [{v.source}]{detail}")
    return 0


if __name__ == "__main__":  # pragma: no cover
    import sys
    raise SystemExit(_cli(sys.argv[1:]))
