"""Grounding data for the unknown_param escalation guard.

Loads the committed dataset (klipper_param_coverage.json, regenerated by
scripts/derive_klipper_param_coverage.py) once per process and answers two
questions for the validator:

  has_record(sec_type)      — does KWC have ground truth for this section?
  param_known(sec_type, k)  — is option `k` in that section's record?

The dataset is a deliberate SUPERSET of what Klipper accepts (common bus
reads reach a section through its module closure): a false negative here
weakens escalation for one section, while a false positive would block a
config Klipper loads. Absence of a section is load-bearing — third-party,
Moonraker-owned, and dynamically-named sections carry no record precisely so
the guard can never ground a claim against them.
"""
from __future__ import annotations

import json
import threading
from pathlib import Path

_DATASET_PATH = Path(__file__).resolve().parent / "klipper_param_coverage.json"

_lock = threading.Lock()
_cache: dict[str, frozenset[str]] | None = None


def _load() -> dict[str, frozenset[str]]:
    global _cache
    if _cache is not None:
        return _cache
    with _lock:
        if _cache is None:
            try:
                data = json.loads(_DATASET_PATH.read_text(encoding="utf-8"))
                _cache = {
                    sec: frozenset(rec.get("params", ()))
                    for sec, rec in data.get("sections", {}).items()
                }
            except (OSError, ValueError):
                # A missing/corrupt dataset must degrade to "no ground truth
                # anywhere" (everything stays a warning), never raise inside
                # validation and never block a save.
                _cache = {}
    return _cache


def has_record(sec_type: str) -> bool:
    """True when the dataset carries ground truth for this section type."""
    return sec_type in _load()


def param_known(sec_type: str, param: str) -> bool:
    """True when `param` (exact, lowercase-normalized) is in the record.

    Callers pass keys already lowercased; Klipper lowercases configfile
    options (configfile.py:433-438) and the generator normalized on write.
    """
    return param.lower() in _load().get(sec_type, frozenset())
